//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://iws.concordfax.com/InboundWS/", ConfigurationName="ServiceReference1.InboundWSSoap")]
    public interface InboundWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://iws.concordfax.com/InboundWS/GetInboundItemsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetInboundItemsByIDResponse1> GetInboundItemsByIDAsync(ServiceReference1.GetInboundItemsByIDRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://iws.concordfax.com/InboundWS/GetInboundItemsByIDEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetInboundItemsByIDExResponse1> GetInboundItemsByIDExAsync(ServiceReference1.GetInboundItemsByIDExRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://iws.concordfax.com/InboundWS/GetInboundItemList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetInboundItemListResponse1> GetInboundItemListAsync(ServiceReference1.GetInboundItemListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://iws.concordfax.com/InboundWS/RemoveInboundItemsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.RemoveInboundItemsByIDResponse1> RemoveInboundItemsByIDAsync(ServiceReference1.RemoveInboundItemsByIDRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class Authentication
    {
        
        private string userIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="InboundWS")]
    public partial class RemoveInboundItemsByIDResponse
    {
        
        private string[] failedItemIDsField;
        
        private int failureCountField;
        
        private bool successField;
        
        private WSError[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] FailedItemIDs
        {
            get
            {
                return this.failedItemIDsField;
            }
            set
            {
                this.failedItemIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int FailureCount
        {
            get
            {
                return this.failureCountField;
            }
            set
            {
                this.failureCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public WSError[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class WSError
    {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class RemoveInboundItemsByIDRequest
    {
        
        private bool doNotArchiveItemsField;
        
        private string[] inboundItemIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool DoNotArchiveItems
        {
            get
            {
                return this.doNotArchiveItemsField;
            }
            set
            {
                this.doNotArchiveItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] InboundItemIDs
        {
            get
            {
                return this.inboundItemIDsField;
            }
            set
            {
                this.inboundItemIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class GetInboundItemListResponse
    {
        
        private string[] inboundItemIDsField;
        
        private int inboundItemCountField;
        
        private bool successField;
        
        private WSError[] messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] InboundItemIDs
        {
            get
            {
                return this.inboundItemIDsField;
            }
            set
            {
                this.inboundItemIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int InboundItemCount
        {
            get
            {
                return this.inboundItemCountField;
            }
            set
            {
                this.inboundItemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public WSError[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class GetInboundItemListRequest
    {
        
        private int maxItemsField;
        
        private string dnisField;
        
        private bool archivedItemsField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaxItems
        {
            get
            {
                return this.maxItemsField;
            }
            set
            {
                this.maxItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Dnis
        {
            get
            {
                return this.dnisField;
            }
            set
            {
                this.dnisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool ArchivedItems
        {
            get
            {
                return this.archivedItemsField;
            }
            set
            {
                this.archivedItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class InboundItemEx
    {
        
        private string userIDField;
        
        private InboundItemDocumentEx documentField;
        
        private DIMESettings dimeSettingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InboundItemDocumentEx Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DIMESettings DimeSettings
        {
            get
            {
                return this.dimeSettingsField;
            }
            set
            {
                this.dimeSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class InboundItemDocumentEx : InboundItemDocument
    {
        
        private string payLoadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PayLoad
        {
            get
            {
                return this.payLoadField;
            }
            set
            {
                this.payLoadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InboundItemDocumentEx))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class InboundItemDocument
    {
        
        private string billingCodeField;
        
        private string calledNumberField;
        
        private string callerNumberField;
        
        private string remoteCSIDField;
        
        private string messageIDField;
        
        private System.DateTime receivedTimeField;
        
        private string speedField;
        
        private string durationField;
        
        private string numPagesField;
        
        private string statusField;
        
        private string contentTypeField;
        
        private string contentSubTypeField;
        
        private string resolutionField;
        
        private string fileNameField;
        
        private byte[] fileDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BillingCode
        {
            get
            {
                return this.billingCodeField;
            }
            set
            {
                this.billingCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CalledNumber
        {
            get
            {
                return this.calledNumberField;
            }
            set
            {
                this.calledNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CallerNumber
        {
            get
            {
                return this.callerNumberField;
            }
            set
            {
                this.callerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RemoteCSID
        {
            get
            {
                return this.remoteCSIDField;
            }
            set
            {
                this.remoteCSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime ReceivedTime
        {
            get
            {
                return this.receivedTimeField;
            }
            set
            {
                this.receivedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Speed
        {
            get
            {
                return this.speedField;
            }
            set
            {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NumPages
        {
            get
            {
                return this.numPagesField;
            }
            set
            {
                this.numPagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ContentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ContentSubType
        {
            get
            {
                return this.contentSubTypeField;
            }
            set
            {
                this.contentSubTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Resolution
        {
            get
            {
                return this.resolutionField;
            }
            set
            {
                this.resolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=14)]
        public byte[] FileData
        {
            get
            {
                return this.fileDataField;
            }
            set
            {
                this.fileDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class DIMESettings
    {
        
        private bool encryptedItemField;
        
        private ItemSecretKey[] itemSecretKeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool EncryptedItem
        {
            get
            {
                return this.encryptedItemField;
            }
            set
            {
                this.encryptedItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ItemSecretKey[] ItemSecretKeys
        {
            get
            {
                return this.itemSecretKeysField;
            }
            set
            {
                this.itemSecretKeysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class ItemSecretKey
    {
        
        private byte[] initiVectorField;
        
        private byte[] initKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] InitiVector
        {
            get
            {
                return this.initiVectorField;
            }
            set
            {
                this.initiVectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] InitKey
        {
            get
            {
                return this.initKeyField;
            }
            set
            {
                this.initKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class GetInboundItemsByIDExResponse
    {
        
        private InboundItemEx[] inboundItemsField;
        
        private int inboundItemCountField;
        
        private bool successField;
        
        private WSError[] messagesField;
        
        private int failureCountField;
        
        private string[] failedItemIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InboundItemEx[] InboundItems
        {
            get
            {
                return this.inboundItemsField;
            }
            set
            {
                this.inboundItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int InboundItemCount
        {
            get
            {
                return this.inboundItemCountField;
            }
            set
            {
                this.inboundItemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public WSError[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FailureCount
        {
            get
            {
                return this.failureCountField;
            }
            set
            {
                this.failureCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] FailedItemIDs
        {
            get
            {
                return this.failedItemIDsField;
            }
            set
            {
                this.failedItemIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class GetInboundItemsByIDExRequest
    {
        
        private string[] inboundItemIDsField;
        
        private ItemRequestSettings reqSettingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] InboundItemIDs
        {
            get
            {
                return this.inboundItemIDsField;
            }
            set
            {
                this.inboundItemIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ItemRequestSettings ReqSettings
        {
            get
            {
                return this.reqSettingsField;
            }
            set
            {
                this.reqSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class ItemRequestSettings
    {
        
        private DIMESettings dimeSettingsField;
        
        private ItemSecurityRequest itemSecurityModeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DIMESettings DimeSettings
        {
            get
            {
                return this.dimeSettingsField;
            }
            set
            {
                this.dimeSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ItemSecurityRequest ItemSecurityMode
        {
            get
            {
                return this.itemSecurityModeField;
            }
            set
            {
                this.itemSecurityModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class ItemSecurityRequest
    {
        
        private bool chunkedField;
        
        private bool digitallySignedField;
        
        private bool ecryptedField;
        
        private string encryptionTypeField;
        
        private bool useDIMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Chunked
        {
            get
            {
                return this.chunkedField;
            }
            set
            {
                this.chunkedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool DigitallySigned
        {
            get
            {
                return this.digitallySignedField;
            }
            set
            {
                this.digitallySignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Ecrypted
        {
            get
            {
                return this.ecryptedField;
            }
            set
            {
                this.ecryptedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EncryptionType
        {
            get
            {
                return this.encryptionTypeField;
            }
            set
            {
                this.encryptionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool UseDIME
        {
            get
            {
                return this.useDIMEField;
            }
            set
            {
                this.useDIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class InboundItem
    {
        
        private string userIDField;
        
        private InboundItemDocument documentField;
        
        private DIMESettings dimeSettingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public InboundItemDocument Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DIMESettings DimeSettings
        {
            get
            {
                return this.dimeSettingsField;
            }
            set
            {
                this.dimeSettingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class GetInboundItemsByIDResponse
    {
        
        private InboundItem[] inboundItemsField;
        
        private int inboundItemCountField;
        
        private bool successField;
        
        private WSError[] messagesField;
        
        private int failureCountField;
        
        private string[] failedItemIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public InboundItem[] InboundItems
        {
            get
            {
                return this.inboundItemsField;
            }
            set
            {
                this.inboundItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int InboundItemCount
        {
            get
            {
                return this.inboundItemCountField;
            }
            set
            {
                this.inboundItemCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public WSError[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FailureCount
        {
            get
            {
                return this.failureCountField;
            }
            set
            {
                this.failureCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] FailedItemIDs
        {
            get
            {
                return this.failedItemIDsField;
            }
            set
            {
                this.failedItemIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://iws.concordfax.com/InboundWS/")]
    public partial class GetInboundItemsByIDRequest
    {
        
        private string[] inboundItemIDsField;
        
        private ItemRequestSettings reqSettingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] InboundItemIDs
        {
            get
            {
                return this.inboundItemIDsField;
            }
            set
            {
                this.inboundItemIDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ItemRequestSettings ReqSettings
        {
            get
            {
                return this.reqSettingsField;
            }
            set
            {
                this.reqSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboundItemsByID", WrapperNamespace="https://iws.concordfax.com/InboundWS/", IsWrapped=true)]
    public partial class GetInboundItemsByIDRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=0)]
        public ServiceReference1.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=1)]
        public ServiceReference1.GetInboundItemsByIDRequest request;
        
        public GetInboundItemsByIDRequest1()
        {
        }
        
        public GetInboundItemsByIDRequest1(ServiceReference1.Authentication authentication, ServiceReference1.GetInboundItemsByIDRequest request)
        {
            this.authentication = authentication;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboundItemsByIDResponse", WrapperNamespace="InboundWS", IsWrapped=true)]
    public partial class GetInboundItemsByIDResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="InboundWS", Order=0)]
        public ServiceReference1.GetInboundItemsByIDResponse GetInboundItemsByIDResult;
        
        public GetInboundItemsByIDResponse1()
        {
        }
        
        public GetInboundItemsByIDResponse1(ServiceReference1.GetInboundItemsByIDResponse GetInboundItemsByIDResult)
        {
            this.GetInboundItemsByIDResult = GetInboundItemsByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboundItemsByIDEx", WrapperNamespace="https://iws.concordfax.com/InboundWS/", IsWrapped=true)]
    public partial class GetInboundItemsByIDExRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=0)]
        public ServiceReference1.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=1)]
        public ServiceReference1.GetInboundItemsByIDExRequest request;
        
        public GetInboundItemsByIDExRequest1()
        {
        }
        
        public GetInboundItemsByIDExRequest1(ServiceReference1.Authentication authentication, ServiceReference1.GetInboundItemsByIDExRequest request)
        {
            this.authentication = authentication;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboundItemsByIDExResponse", WrapperNamespace="InboundWS", IsWrapped=true)]
    public partial class GetInboundItemsByIDExResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="InboundWS", Order=0)]
        public ServiceReference1.GetInboundItemsByIDExResponse GetInboundItemsByIDExResult;
        
        public GetInboundItemsByIDExResponse1()
        {
        }
        
        public GetInboundItemsByIDExResponse1(ServiceReference1.GetInboundItemsByIDExResponse GetInboundItemsByIDExResult)
        {
            this.GetInboundItemsByIDExResult = GetInboundItemsByIDExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboundItemList", WrapperNamespace="https://iws.concordfax.com/InboundWS/", IsWrapped=true)]
    public partial class GetInboundItemListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=0)]
        public ServiceReference1.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=1)]
        public ServiceReference1.GetInboundItemListRequest request;
        
        public GetInboundItemListRequest1()
        {
        }
        
        public GetInboundItemListRequest1(ServiceReference1.Authentication authentication, ServiceReference1.GetInboundItemListRequest request)
        {
            this.authentication = authentication;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInboundItemListResponse", WrapperNamespace="InboundWS", IsWrapped=true)]
    public partial class GetInboundItemListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="InboundWS", Order=0)]
        public ServiceReference1.GetInboundItemListResponse GetInboundItemListResult;
        
        public GetInboundItemListResponse1()
        {
        }
        
        public GetInboundItemListResponse1(ServiceReference1.GetInboundItemListResponse GetInboundItemListResult)
        {
            this.GetInboundItemListResult = GetInboundItemListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveInboundItemsByID", WrapperNamespace="https://iws.concordfax.com/InboundWS/", IsWrapped=true)]
    public partial class RemoveInboundItemsByIDRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=0)]
        public ServiceReference1.Authentication authentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://iws.concordfax.com/InboundWS/", Order=1)]
        public ServiceReference1.RemoveInboundItemsByIDRequest request;
        
        public RemoveInboundItemsByIDRequest1()
        {
        }
        
        public RemoveInboundItemsByIDRequest1(ServiceReference1.Authentication authentication, ServiceReference1.RemoveInboundItemsByIDRequest request)
        {
            this.authentication = authentication;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveInboundItemsByIDResponse", WrapperNamespace="InboundWS", IsWrapped=true)]
    public partial class RemoveInboundItemsByIDResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="InboundWS", Order=0)]
        public ServiceReference1.RemoveInboundItemsByIDResponse RemoveInboundItemsByIDResult;
        
        public RemoveInboundItemsByIDResponse1()
        {
        }
        
        public RemoveInboundItemsByIDResponse1(ServiceReference1.RemoveInboundItemsByIDResponse RemoveInboundItemsByIDResult)
        {
            this.RemoveInboundItemsByIDResult = RemoveInboundItemsByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface InboundWSSoapChannel : ServiceReference1.InboundWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class InboundWSSoapClient : System.ServiceModel.ClientBase<ServiceReference1.InboundWSSoap>, ServiceReference1.InboundWSSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InboundWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(InboundWSSoapClient.GetBindingForEndpoint(endpointConfiguration), InboundWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InboundWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InboundWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InboundWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InboundWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InboundWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetInboundItemsByIDResponse1> ServiceReference1.InboundWSSoap.GetInboundItemsByIDAsync(ServiceReference1.GetInboundItemsByIDRequest1 request)
        {
            return base.Channel.GetInboundItemsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetInboundItemsByIDResponse1> GetInboundItemsByIDAsync(ServiceReference1.Authentication authentication, ServiceReference1.GetInboundItemsByIDRequest request)
        {
            ServiceReference1.GetInboundItemsByIDRequest1 inValue = new ServiceReference1.GetInboundItemsByIDRequest1();
            inValue.authentication = authentication;
            inValue.request = request;
            return ((ServiceReference1.InboundWSSoap)(this)).GetInboundItemsByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetInboundItemsByIDExResponse1> ServiceReference1.InboundWSSoap.GetInboundItemsByIDExAsync(ServiceReference1.GetInboundItemsByIDExRequest1 request)
        {
            return base.Channel.GetInboundItemsByIDExAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetInboundItemsByIDExResponse1> GetInboundItemsByIDExAsync(ServiceReference1.Authentication authentication, ServiceReference1.GetInboundItemsByIDExRequest request)
        {
            ServiceReference1.GetInboundItemsByIDExRequest1 inValue = new ServiceReference1.GetInboundItemsByIDExRequest1();
            inValue.authentication = authentication;
            inValue.request = request;
            return ((ServiceReference1.InboundWSSoap)(this)).GetInboundItemsByIDExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetInboundItemListResponse1> ServiceReference1.InboundWSSoap.GetInboundItemListAsync(ServiceReference1.GetInboundItemListRequest1 request)
        {
            return base.Channel.GetInboundItemListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetInboundItemListResponse1> GetInboundItemListAsync(ServiceReference1.Authentication authentication, ServiceReference1.GetInboundItemListRequest request)
        {
            ServiceReference1.GetInboundItemListRequest1 inValue = new ServiceReference1.GetInboundItemListRequest1();
            inValue.authentication = authentication;
            inValue.request = request;
            return ((ServiceReference1.InboundWSSoap)(this)).GetInboundItemListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RemoveInboundItemsByIDResponse1> ServiceReference1.InboundWSSoap.RemoveInboundItemsByIDAsync(ServiceReference1.RemoveInboundItemsByIDRequest1 request)
        {
            return base.Channel.RemoveInboundItemsByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemoveInboundItemsByIDResponse1> RemoveInboundItemsByIDAsync(ServiceReference1.Authentication authentication, ServiceReference1.RemoveInboundItemsByIDRequest request)
        {
            ServiceReference1.RemoveInboundItemsByIDRequest1 inValue = new ServiceReference1.RemoveInboundItemsByIDRequest1();
            inValue.authentication = authentication;
            inValue.request = request;
            return ((ServiceReference1.InboundWSSoap)(this)).RemoveInboundItemsByIDAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InboundWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.InboundWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InboundWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://iws.concordfax.com/inboundws/v1/inboundws.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.InboundWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://iws.concordfax.com/inboundws/v1/inboundws.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            InboundWSSoap,
            
            InboundWSSoap12,
        }
    }
}
